ARG BUILD_FROM=ghcr.io/turkflix/bom-interactive-proxy:latest
FROM ${BUILD_FROM}

LABEL \
  io.hass.name="BOM Interactive Proxy" \
  io.hass.description="BOM interactive weather map proxy" \
  io.hass.type="addon"
